import {Sidebar,Topbar,MobileNav} from '../App';
import {EWaste} from '../EWaste';
import {useEffect,useState} from 'react';
import {supabase,api,signIn,signUp,signOut,uploadMedia,signedMedia} from './supabase';
import {Products,Orders,Components,Revenue} from '../Marketplace';
import {ComponentCapture,Assistant,ProfileEditor,emptyProfile,type Profile} from '../SellerFeatures';
import {SellerHome,ProjectLibrary} from '../ProjectLibrary';
import {initialMarket,type Market,type Listing,type Order} from '../market';
import type {User} from '@supabase/supabase-js';
type Row=Record<string,any>;
export default function CloudApp(){
 const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[role,setRole]=useState<'buyer'|'seller'>('buyer');const[allowedRole,setAllowedRole]=useState('');const[view,setView]=useState('home');const[market,setMarket]=useState<Market>(initialMarket);const[message,setMessage]=useState('');const[scan,setScan]=useState(false);const[manual,setManual]=useState(false);const[search,setSearch]=useState('');const[inventory,setInventory]=useState<Listing[]>([]);const[grams,setGrams]=useState(0);const[ready,setReady]=useState(false);
 function notice(e:unknown){setMessage(e instanceof Error?e.message:'Request failed');}
 async function loadProfile(){const rows=await api<Row[]>('/api/profile');if(rows[0]){const p=rows[0];setAllowedRole(p.role);setRole(p.role==='seller'?'seller':'buyer');setProfile({...emptyProfile,...p.details,name:p.name,email:(await supabase!.auth.getUser()).data.user?.email||''});}}
 async function refresh(){if(role==='buyer'){const owned=await api<Row[]>('/api/inventory');setInventory(owned.map(o=>({...o.metadata,id:o.id,name:o.name,quantity:Number(o.quantity),weightG:Number(o.weight_g||0),archived:false} as Listing)));}const [listings,orders,events]=await Promise.all([api<Row[]>(`/api/listings?own=${role==='seller'}`),api<Row[]>('/api/orders'),api<Row[]>('/api/impact')]);const hydrated:Row[]=await Promise.all(listings.map(async (l:Row)=>({...l,metadata:{...l.metadata,image:await signedMedia(l.metadata.media_paths?.[0]||''),images:await Promise.all((l.metadata.media_paths||[]).map(signedMedia)),video:await signedMedia(l.metadata.video_path||'')}})));setMarket({listings:hydrated.map(l=>({...l.metadata,id:l.id,name:l.name,quantity:l.quantity,condition:l.condition,mode:l.mode,price:Number(l.price),archived:l.archived,weightG:Number(l.weight_g||0),maxDays:l.max_days,deposit:Number(l.deposit)} as Listing)),orders:orders.map(o=>({id:o.id,listingId:o.listing_id,name:o.name,mode:o.mode,quantity:o.quantity,days:o.days,amount:Number(o.amount),buyerConfirmed:o.buyer_confirmed,sellerConfirmed:o.seller_confirmed,status:o.status} as Order))});setGrams(events.reduce((n,e)=>n+Number(e.reuse_g),0));}
 useEffect(()=>{supabase!.auth.getSession().then(({data})=>{setUser(data.session?.user||null);setReady(true);});const{data:{subscription}}=supabase!.auth.onAuthStateChange((_event,session)=>{setUser(session?.user||null);setProfile(null);setMarket(initialMarket);setGrams(0);});return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{if(user?.email_confirmed_at)loadProfile().catch(notice);},[user]);
 useEffect(()=>{if(profile)refresh().catch(notice);},[profile,role]);
 if(!ready)return <main className="feature-page">Loading session…</main>;
 if(!user)return <CloudLogin notify={setMessage} message={message}/>;
 if(!user.email_confirmed_at)return <main className="feature-page"><h1>Confirm your email</h1><p>Open your Supabase confirmation email, then return here.</p><button onClick={()=>signOut()}>Sign out</button></main>;
 if(!profile)return <main className="feature-page"><h1>Set up your ReCircuit profile</h1><p>Email: {user.email}</p>{message&&<p role="alert">{message}</p>}<form className="form-grid" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/profile','POST',{name:f.get('name'),role:f.get('role'),details:{}});await loadProfile();setMessage('');}catch(e){notice(e);}}}><label className="field-label">Name<input name="name" required defaultValue={user.user_metadata.name||''}/></label><label className="field-label">Usage mode<select name="role"><option value="buyer">Buyer</option><option value="seller">Seller</option><option value="both">Both</option></select></label><button className="button button-primary">Continue</button></form><button onClick={()=>signOut()}>Sign out</button></main>;
 async function add(l:Listing){
   const urls:string[]=[];for(const value of l.images||[l.image]){if(!value)continue;const blob=await (await fetch(value)).blob();urls.push(await uploadMedia(new File([blob],'component',{type:blob.type})));}
   let videoPath='';if(l.video){const blob=await(await fetch(l.video)).blob();videoPath=await uploadMedia(new File([blob],'clip',{type:blob.type}));}
   const {image,images,video,...metadata}=l;
   await api('/api/listings','POST',{name:l.name,quantity:l.quantity,mode:l.mode,price:l.price,condition:l.condition,weight_g:l.weightG||null,max_days:l.mode==='Rent'?l.maxDays:null,deposit:l.deposit||0,metadata:{...metadata,image:'',images:[],video:'',media_paths:urls,video_path:videoPath}});await refresh();
 }
 async function order(id:string,q:number,d:number){await api('/api/orders','POST',{listing_id:id,quantity:q,days:d,request_id:crypto.randomUUID()});await refresh();}
 async function action(id:string,type:string){try{await api(`/api/orders/${id}/${type}`,'POST');await refresh();setMessage('');}catch(e){notice(e);}}
 return <div className={`app-shell role-${role}`}><Sidebar view={view} go={setView} role={role} signOut={()=>{void signOut();}}/><div className="main-shell"><Topbar role={role} openScan={()=>setScan(true)} goMarket={()=>setView('marketplace')}/><main><header className="feature-actions"><h1>ReCircuit</h1><span>{profile.name} · {role}</span>{allowedRole==='both'&&<button className="button button-secondary" onClick={()=>{setRole(role==='seller'?'buyer':'seller');setView('home');}}>Switch workspace</button>}<button className="button button-secondary" onClick={()=>signOut()}>Sign out</button></header><nav className="feature-actions">{['home',role==='seller'?'listings':'components','orders',...(role==='seller'?['revenue']:[]),'rentals','donations','history','handover','ewaste','projects','assistant','impact','profile'].map(v=><button className={`button ${view===v?'button-primary':'button-secondary'}`} key={v} onClick={()=>setView(v)}>{v}</button>)}</nav>{message&&<p role="alert">{message}</p>}
 {view==='home'&&role==='seller'&&<SellerHome market={market} name={profile.name} grams={grams} scan={()=>{setManual(false);setScan(true);}} manual={()=>{setManual(true);setScan(true);}} projects={()=>setView('projects')}/>}
 {(view==='marketplace'||view==='listings'||(view==='home'&&role==='buyer'))&&<Products key={search} search={search} own={view==='listings'} market={market} order={order} archive={id=>{const l=market.listings.find(x=>x.id===id);api(`/api/listings/${id}/archive?archived=${!l?.archived}`,'PATCH').then(refresh).catch(notice);}} add={()=>setScan(true)}/>}
 {view==='orders'&&<Orders market={market} role={role} confirm={id=>{void action(id,'confirm');}} cancel={id=>{void action(id,'cancel');}}/>}{view==='revenue'&&<Revenue market={market}/>} {view==='components'&&<Components market={market}/>}
 {['rentals','donations','history','handover'].includes(view)&&<Orders market={market} role={role} filter={view==='rentals'?'Rent':view==='donations'?'Donate':view==='history'?'History':'Handover'} confirm={id=>{void action(id,'confirm');}} cancel={id=>{void action(id,'cancel');}}/>}
 {view==='ewaste'&&<EWaste submit={async data=>{const blob=await(await fetch(data.image)).blob();const path=await uploadMedia(new File([blob],'ewaste',{type:blob.type}));await api('/api/ewaste','POST',{route:data.route,weight_g:data.weight||null,media_path:path,quoted_rate_per_kg:data.rate,quote_source:data.source||null});}}/>}
 {view==='projects'&&<ProjectLibrary market={role==='buyer'?{...market,listings:inventory}:market} find={name=>{setSearch(name);setView('marketplace');}}/>}
 {view==='assistant'&&<Assistant/>}{view==='impact'&&<section className="feature-page"><h1>Recorded reused mass: {grams} g</h1><p>Completed handovers, using seller-declared mass. No forecast or CO₂ claims.</p></section>}
 {view==='profile'&&<ProfileEditor profile={profile} save={p=>{const{name,email,...details}=p;api('/api/profile','PATCH',{name,role:allowedRole,details}).then(()=>{setProfile(p);setMessage('Profile saved');}).catch(notice);}}/>}
 {scan&&<ComponentCapture close={()=>setScan(false)} manual={manual} projects={()=>setView('projects')} publish={add}/>}
 </main></div><MobileNav role={role} view={view} go={setView} openScan={()=>role==='seller'?setScan(true):setView('marketplace')}/></div>;
}
function CloudLogin({message,notify}:{message:string;notify:(m:string)=>void}){const[signup,setSignup]=useState(false);const[busy,setBusy]=useState(false);return <main className="feature-page"><h1>{signup?'Create ReCircuit account':'Sign in to ReCircuit'}</h1><p>Supabase authentication · Email confirmation required</p><form className="form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const result=signup?await signUp(String(f.get('email')),String(f.get('password')),String(f.get('name'))):await signIn(String(f.get('email')),String(f.get('password')));if(result.error)throw result.error;notify(signup?'Check your email to confirm your account.':'');}catch(e){notify(e instanceof Error?e.message:'Authentication failed');}finally{setBusy(false);}}}>{signup&&<label className="field-label">Name<input required name="name"/></label>}<label className="field-label">Email<input required name="email" type="email" autoComplete="email"/></label><label className="field-label">Password<input required minLength={8} name="password" type="password" autoComplete={signup?'new-password':'current-password'}/></label><button className="button button-primary" disabled={busy}>{busy?'Please wait…':signup?'Sign up':'Log in'}</button></form>{message&&<p role="status">{message}</p>}<button className="button button-secondary" onClick={()=>setSignup(!signup)}>{signup?'Already registered? Log in':'Create an account'}</button></main>;}
