import {useEffect,useRef,useState} from 'react';
type Submission={id:string;route:'Sell'|'Contribute';weight:number;image:string;estimatedPrice:number|null;source:string};
export function EWaste({submit}:{submit?:(data:{image:string;route:'Sell'|'Contribute';weight:number;rate:number|null;source:string})=>Promise<void>}={}){
 const[route,setRoute]=useState<'Sell'|'Contribute'>('Sell');const[image,setImage]=useState('');const[weight,setWeight]=useState('');const[rate,setRate]=useState('');const[source,setSource]=useState('');const[error,setError]=useState('');const[done,setDone]=useState<Submission|null>(null);const[live,setLive]=useState(false);const[history,setHistory]=useState<Submission[]>([]);
 const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);
 const stop=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());},[]);
 useEffect(()=>{if(live&&video.current)video.current.srcObject=stream.current;},[live]);
 async function camera(){setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera requires HTTPS or localhost. Upload a photo instead.');stop();stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});setLive(true);}catch(e){setError(e instanceof Error?e.message:'Camera unavailable.');}}
 function capture(){const v=video.current;if(!v?.videoWidth){setError('Wait for the camera before capture.');return;}const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d')?.drawImage(v,0,0);setImage(c.toDataURL('image/jpeg',.8));stop();setLive(false);}
 function upload(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){setError('Choose JPG, PNG or WebP under 8 MB.');return;}stop();setLive(false);setError('');const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(file);}
 const grams=Number(weight);const value=rate.trim()&&Number.isFinite(Number(rate))?grams/1000*Number(rate):null;
 return <section className="section-block feature-page"><span className="overline">Seller & buyer · E-waste</span><h1>Give nature a cleaner future.</h1><p>Photograph electronics that cannot be reused, then choose Sell or Contribute. Reusable items should go through component listings first.</p><p className="test-data-note">Demo routing request only. Recycler collection, payment and actual recycling are not connected. Submission does not count as waste recycled.</p>
 {done?<div className="ai-note" role="status"><h2>{done.route==='Sell'?'Thank you for taking a step toward a cleaner world!':'Thank you so much for your thoughtful contribution to nature!'}</h2><p>{done.route==='Sell'?`${done.weight} g recorded for a demo recycling sale. ${done.estimatedPrice===null?'Price awaits a recycler quote.':`Estimated value: ₹${done.estimatedPrice.toFixed(2)} using your supplied rate.`}`:'Your willingness to contribute helps encourage responsible disposal and care for our environment.'}</p><p>Arrange handover with an authorized recycler. No pickup or environmental outcome has been verified.</p><button className="button button-primary" onClick={()=>{setDone(null);setImage('');setWeight('');setRate('');setSource('');}}>Submit another item</button></div>:<>
 <div className="feature-actions"><button className="button button-primary" onClick={camera}>Click photo · Open camera</button><label className="button button-secondary">Upload photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label></div>
 {live&&<><video ref={video} autoPlay playsInline muted className="capture-preview"/><button className="button button-primary" onClick={capture}>Capture photo</button><button className="button button-secondary" onClick={()=>{stop();setLive(false);}}>Stop camera</button></>}{image&&<img src={image} alt="E-waste photographed for routing" className="capture-preview"/>}
 <form className="form-grid" onSubmit={async e=>{e.preventDefault();if(!image){setError('Capture or upload a photo first.');return;}if(route==='Sell'&&(!Number.isFinite(grams)||grams<500)){setError('Minimum weight for selling in this prototype is 500 g.');return;}if(route==='Sell'&&rate.trim()&&(!Number.isFinite(Number(rate))||Number(rate)<0||!source.trim())){setError('Enter a non-negative rate and identify its recycler/source.');return;}const submission:Submission={id:crypto.randomUUID(),route,weight:Number.isFinite(grams)?grams:0,image,estimatedPrice:route==='Sell'?value:null,source};try{if(submit)await submit({image,route,weight:submission.weight,rate:rate.trim()?Number(rate):null,source});}catch(e){setError(e instanceof Error?e.message:'Submission failed');return;}setHistory(h=>[submission,...h]);setDone(submission);stop();setLive(false);setError('');}}>
 <label className="field-label full-field">What would you like to do?<select value={route} onChange={e=>{setRoute(e.target.value as 'Sell'|'Contribute');setError('');}}><option>Sell</option><option>Contribute</option></select></label>
 <label className="field-label">Weight (grams){route==='Sell'?' · Minimum 500 g':' · Optional'}<input required={route==='Sell'} type="number" min={route==='Sell'?500:0} step="1" value={weight} onChange={e=>setWeight(e.target.value)}/></label>
 {route==='Sell'&&<><label className="field-label">Recycler quoted rate (₹ / kg, optional)<input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><label className="field-label full-field">Rate source / recycler and quote date<input required={!!rate.trim()} value={source} onChange={e=>setSource(e.target.value)} placeholder="Recycler name, material category and dated quote"/></label><p className="full-field">{value===null?'Market price unavailable: request a current recycler quote.':`Estimated value: ₹${value.toFixed(2)} = ${(grams/1000).toFixed(3)} kg × ₹${Number(rate).toFixed(2)}/kg. User-supplied quote; not independently verified.`}</p><p className="legal-copy full-field">Rates vary by material and condition. The 500 g minimum is this prototype’s rule.</p></>}
 {error&&<p role="alert" className="full-field">{error}</p>}<button className="button button-primary">{route==='Sell'?'Submit demo sale request':'Contribute for a cleaner world'}</button></form></>}
 {history.length>0&&<div className="section-block"><h2>Requests during this page visit</h2>{history.map(h=><p key={h.id}>{h.route} · {h.weight} g · Demo request recorded</p>)}</div>}
 </section>;
}
