import {normalize} from './project-engine';
import {useState} from 'react';
import {type Listing,type Market} from './market';
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n);
export function Products({market,own=false,search="",order,archive,add}:{market:Market;own?:boolean;search?:string;order:(id:string,q:number,d:number)=>void | Promise<void>;archive:(id:string)=>void;add:()=>void}) {
 const [query,setQuery]=useState(search);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const listings=market.listings.filter(l=>(own || (!l.archived&&l.quantity>0))&&([l.name,l.previousProject,l.tags,l.description,l.category,l.searchKeywords,l.applications,l.title].join(" ").toLowerCase().includes(query.toLowerCase()) || normalize(l.name)===normalize(query)));
 return <section className="section-block feature-page"><span className="overline">{own?'Seller inventory':'Buyer marketplace'}</span><h1>{own?'My listings':'Find your next component'}</h1><p>{own?'Manage the products you have published.':'Browse every available seller listing. Buy, rent or claim a donation.'}</p><div className="feature-actions"><label className="field-label chat-input">Search products<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search seller products" /></label>{own&&<button className="button button-primary" onClick={add}>Add listing</button>}</div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {!listings.length&&<p>No {own?'listings yet. Add your first component.':'products available yet. Publish a listing from the seller workspace.'}</p>}
 <div className="product-grid">{listings.map(l=><Product key={l.id} listing={l} own={own} archive={()=>archive(l.id)} order={async (q,d)=>{try{await order(l.id,q,d);setError('');setNotice('Order reserved. Open Orders to complete both demo handover confirmations.');}catch(e){setError(e instanceof Error?e.message:'Order failed.');}}} />)}</div></section>;
}
function Product({listing:l,own,order,archive}:{listing:Listing;own:boolean;order:(q:number,d:number)=>void | Promise<void>;archive:()=>void}){
 const[q,setQ]=useState(1);const[d,setD]=useState(1);const[busy,setBusy]=useState(false);
 return <article className="product-card">{l.image?<img src={l.image} alt={l.name}/>:<div className="product-empty">♻</div>}<h2>{l.title || l.name}</h2><p>{l.condition}</p><p>{l.description}</p>{l.video&&<video src={l.video} controls className="capture-preview"/>}{l.images&&l.images.length>1&&<div className="feature-actions">{l.images.slice(1).map((src,i)=><img className="profile-preview" key={i} src={src} alt={`${l.name} view ${i+2}`}/>)}</div>}{l.previousProject&&<p>Previously used for: {l.previousProject}</p>}{l.mode==='Rent'&&<p>Max {l.maxDays || 'unspecified'} days · Deposit {money(l.deposit||0)} (DEMO, not collected)</p>}<strong>{l.mode==='Donate'?'Free · Donation':`${money(l.price)}${l.mode==='Rent'?' / day':''}`}</strong><p>{l.quantity} available · {l.archived?'Archived':l.quantity?'Active':'Sold out / Reserved'}</p>{own?<button className="button button-secondary" onClick={archive}>{l.archived?'Restore listing':'Archive listing'}</button>:<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await order(q,d);}finally{setBusy(false);}}}><label className="field-label">Quantity<input required type="number" min="1" max={l.quantity} step="1" value={q} onChange={e=>setQ(Number(e.target.value))}/></label>{l.mode==='Rent'&&<label className="field-label">Rental days<input required type="number" min="1" step="1" value={d} onChange={e=>setD(Number(e.target.value))}/></label>}<p>Total: {money(l.price*q*(l.mode==='Rent'?d:1))} · Demo payment</p><button disabled={busy} className="button button-primary">{l.mode==='Donate'?'Claim free donation':l.mode==='Rent'?'Reserve rental':'Buy component'}</button></form>}</article>;
}
export function Orders({market,role,confirm,cancel,filter}:{filter?:'Rent'|'Donate'|'History'|'Handover';market:Market;role:'buyer'|'seller';confirm:(id:string)=>void;cancel:(id:string)=>void}){
 return <section className="section-block feature-page"><h1>{filter || (role==='seller'?'Seller orders':'My orders')}</h1><p>Shared local demo orders. Complete both buyer and seller handover confirmations. No real payment is collected.</p>{!market.orders.length&&<p>No orders yet.</p>}{market.orders.filter(o=>!filter || (filter==='History'?o.status!=='Reserved':filter==='Handover'?o.status==='Reserved':o.mode===filter)).map(o=><article key={o.id} className="order-card"><h2>{o.name}</h2><p>{o.mode} · {o.quantity} item(s){o.mode==='Rent'?` · ${o.days} days`:''} · {money(o.amount)}</p><strong>{o.status}</strong><p>Buyer: {o.buyerConfirmed?'Confirmed':'Pending'} · Seller: {o.sellerConfirmed?'Confirmed':'Pending'}</p>{o.status==='Reserved'&&<div className="feature-actions"><button className="button button-primary" disabled={role==='buyer'?o.buyerConfirmed:o.sellerConfirmed} onClick={()=>confirm(o.id)}>Confirm {role} handover</button><button className="button button-secondary" onClick={()=>cancel(o.id)}>Cancel reservation</button></div>}</article>)}</section>;
}
export function Revenue({market}:{market:Market}){const completed=market.orders.filter(o=>o.status==='Completed');return <section className="section-block feature-page"><h1>Seller revenue</h1><p>Completed demo handovers only. These are simulated earnings, not money received.</p><div className="stats-grid">{(['Sell','Rent','Donate'] as const).map(mode=><article className="stat-card" key={mode}><div><p>{mode}</p><strong>{money(completed.filter(o=>o.mode===mode).reduce((n,o)=>n+o.amount,0))}</strong><small>{completed.filter(o=>o.mode===mode).length} completed orders</small></div></article>)}</div>{completed.map(o=><p key={o.id}>{o.name} — {money(o.amount)}</p>)}</section>;}
export function Components({market}:{market:Market}){const items=market.orders.filter(o=>o.status==='Completed');return <section className="section-block feature-page"><h1>My components</h1><p>Components received after both handover confirmations. Rentals remain borrowed items.</p>{!items.length&&<p>No received components yet. Browse seller products and complete a handover.</p>}{items.map(o=><article className="order-card" key={o.id}><h2>{o.name}</h2><p>{o.quantity} item(s) · {o.mode==='Rent'?`Borrowed for ${o.days} days`:'Received'} · {o.mode}</p></article>)}</section>;}
