import {useState} from 'react';
import {projectLibrary,match} from './project-engine';
import type {Market} from './market';
export function ProjectLibrary({market,find}:{market:Market;find:(name:string)=>void}){
 const[q,setQ]=useState('');const[category,setCategory]=useState('All');const[selected,setSelected]=useState('');
 const project=projectLibrary.find(p=>p.id===selected);
 if(project){const result=match(project.requirements,market.listings);return <section className="section-block feature-page"><button className="button button-secondary" onClick={()=>setSelected('')}>Back to projects</button><h1>{project.title}</h1><h2>{result.score}% component availability</h2><p>Score = matched units ÷ required units × 100. Availability is not an electrical compatibility or build-safety certification.</p><div className="bar-track"><div className="bar-saved" style={{width:`${result.score}%`}}/></div><div className="bom-table-wrap"><table><thead><tr><th>Component</th><th>Required</th><th>Available</th><th>Missing</th><th>Action</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.name}><td>{r.name}{r.critical?' · Critical':''}</td><td>{r.qty}</td><td>{r.available}</td><td>{r.missing}</td><td>{r.missing>0?<button className="button button-secondary" onClick={()=>find(r.name)}>Find {r.name}</button>:'Available'}</td></tr>)}</tbody></table></div><p>Potential reuse: {result.mass.toFixed(1)} g, based on seller-entered weights. Not yet counted as completed reuse.</p><p>These are prototype BOM templates. Validate voltage/current ratings, connectors, tools and project-specific materials before building.</p></section>;}
 return <section className="section-block feature-page"><h1>Project library</h1><p>Discover projects for your published components. Scores recalculate as inventory changes.</p><div className="feature-actions"><label className="field-label">Search projects<input value={q} onChange={e=>setQ(e.target.value)}/></label><label className="field-label">Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All','Robotics','IoT','Automation','Environment','Home','Education'].map(c=><option key={c}>{c}</option>)}</select></label></div><div className="product-grid">{projectLibrary.filter(p=>(category==='All'||p.category===category)&&p.title.toLowerCase().includes(q.toLowerCase())).map(p=>{const r=match(p.requirements,market.listings);return <article className="product-card" key={p.id}><h2>{p.title}</h2><p>{p.category}</p><strong>{r.score}% component availability</strong><div className="bar-track"><div className="bar-saved" style={{width:`${r.score}%`}}/></div><p>{r.rows.filter(x=>!x.missing).length}/{r.rows.length} component groups complete</p><button className="button button-primary" onClick={()=>setSelected(p.id)}>View project</button></article>;})}</div></section>;
}
export function SellerHome({market,name,grams,scan,manual,projects}:{market:Market;name:string;grams:number;scan:()=>void;manual:()=>void;projects:()=>void}){
 const completed=market.orders.filter(o=>o.status==='Completed');const amount=completed.reduce((n,o)=>n+o.amount,0);
 return <section className="section-block feature-page"><span className="overline">Seller workspace</span><h1>Hello, {name || 'maker'}</h1><h2>Give your components another circuit.</h2><div className="feature-actions"><button className="button button-primary" onClick={scan}>📷 Scan component</button><button className="button button-secondary" onClick={manual}>＋ Add manually</button></div><div className="stats-grid">{[['Components reused',String(completed.reduce((n,o)=>n+o.quantity,0))],['Waste diverted',`${grams} g`],['Earnings',`₹${amount.toLocaleString('en-IN')}`],['Donations',String(completed.filter(o=>o.mode==='Donate').length)]].map(([label,value])=><article key={label} className="stat-card"><div><p>{label}</p><strong>{value}</strong><small>Demo / self-reported</small></div></article>)}</div><div className="workbench-banner"><div><span className="overline">Reuse before disposal</span><h2>♻ A spare part can become a new project.</h2><p>Share its condition and previous project usage. A clear listing helps another maker find it.</p><button className="button button-secondary" onClick={projects}>Explore matching projects</button></div></div></section>;
}
